import Foundation

/// Best-effort YouTube transcript fetcher. Scrapes the watch page for the
/// captions track list, picks the most relevant English track, and fetches
/// the transcript in JSON3 format.
///
/// This is unofficial — YouTube doesn't expose transcripts through the Data
/// API. The watch-page surface changes from time to time, so callers should
/// treat any throw from this as "no transcript available" and proceed with
/// title + description.
enum TranscriptFetcher {
    static func fetch(videoId: String,
                      session: URLSession = .shared) async throws -> String {
        let html = try await fetchWatchPage(videoId: videoId, session: session)
        guard let track = pickEnglishTrack(in: html) else {
            throw TranscriptError.noTracks
        }
        guard var components = URLComponents(string: track.baseURL) else {
            throw TranscriptError.invalidBaseURL
        }
        // Force JSON3 format — easier to parse than the default XML.
        components.queryItems = (components.queryItems ?? []) + [URLQueryItem(name: "fmt", value: "json3")]
        guard let url = components.url else { throw TranscriptError.invalidBaseURL }

        var request = URLRequest(url: url)
        request.setValue(Self.browserUA, forHTTPHeaderField: "User-Agent")
        request.timeoutInterval = 30

        let (data, response) = try await session.data(for: request)
        guard let http = response as? HTTPURLResponse, (200..<300).contains(http.statusCode) else {
            throw TranscriptError.fetchFailed
        }
        return try parseJSON3(data: data)
    }

    // MARK: - Internals

    private static func fetchWatchPage(videoId: String, session: URLSession) async throws -> String {
        guard let url = URL(string: "https://www.youtube.com/watch?v=\(videoId)&hl=en") else {
            throw TranscriptError.invalidBaseURL
        }
        var request = URLRequest(url: url)
        request.setValue(browserUA, forHTTPHeaderField: "User-Agent")
        request.timeoutInterval = 30

        let (data, response) = try await session.data(for: request)
        guard let http = response as? HTTPURLResponse, (200..<300).contains(http.statusCode) else {
            throw TranscriptError.fetchFailed
        }
        guard let html = String(data: data, encoding: .utf8) else {
            throw TranscriptError.fetchFailed
        }
        return html
    }

    private struct CaptionTrack {
        let baseURL: String
        let languageCode: String
        let isAutoGenerated: Bool
    }

    /// Look for `"captionTracks":[ ... ]` in the watch page. Tolerant of
    /// minor whitespace variation.
    private static func pickEnglishTrack(in html: String) -> CaptionTrack? {
        let tracks = extractCaptionTracks(from: html)
        // Prefer manual English, then auto-generated English, then anything.
        if let m = tracks.first(where: { $0.languageCode.hasPrefix("en") && !$0.isAutoGenerated }) {
            return m
        }
        if let a = tracks.first(where: { $0.languageCode.hasPrefix("en") }) {
            return a
        }
        return tracks.first
    }

    private static func extractCaptionTracks(from html: String) -> [CaptionTrack] {
        guard let range = html.range(of: "\"captionTracks\":") else { return [] }
        // The value is a JSON array. Walk forward balancing brackets to find its end.
        let start = range.upperBound
        var depth = 0
        var arrayStart: String.Index?
        var i = start
        while i < html.endIndex {
            let ch = html[i]
            if ch == "[" {
                if arrayStart == nil { arrayStart = i }
                depth += 1
            } else if ch == "]" {
                depth -= 1
                if depth == 0, let s = arrayStart {
                    let arrayJSON = String(html[s...i])
                    return decodeTracks(arrayJSON)
                }
            }
            i = html.index(after: i)
        }
        return []
    }

    private static func decodeTracks(_ json: String) -> [CaptionTrack] {
        guard let data = json.data(using: .utf8) else { return [] }
        struct DTO: Decodable {
            let baseUrl: String
            let languageCode: String
            let kind: String?
        }
        guard let raw = try? JSONDecoder().decode([DTO].self, from: data) else { return [] }
        return raw.map { d in
            CaptionTrack(
                baseURL: d.baseUrl,
                languageCode: d.languageCode,
                isAutoGenerated: d.kind == "asr"
            )
        }
    }

    /// JSON3 transcript shape:
    /// `{"events":[{"segs":[{"utf8":"Hello"}, ...]}, ...]}`
    private static func parseJSON3(data: Data) throws -> String {
        struct JSON3: Decodable {
            let events: [Event]?
            struct Event: Decodable {
                let segs: [Seg]?
            }
            struct Seg: Decodable {
                let utf8: String?
            }
        }
        let parsed = try JSONDecoder().decode(JSON3.self, from: data)
        let events = parsed.events ?? []
        var pieces: [String] = []
        for event in events {
            guard let segs = event.segs else { continue }
            for seg in segs {
                if let s = seg.utf8 { pieces.append(s) }
            }
        }
        let joined = pieces.joined()
            .replacingOccurrences(of: "\n", with: " ")
            .trimmingCharacters(in: .whitespaces)
        guard !joined.isEmpty else { throw TranscriptError.empty }
        return joined
    }

    private static let browserUA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15"
}

enum TranscriptError: Error {
    case noTracks
    case invalidBaseURL
    case fetchFailed
    case empty
}
